# Generated by Django 5.0.7 on 2024-07-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=20)),
                ('views', models.IntegerField()),
                ('pos', models.IntegerField()),
            ],
        ),
    ]
